# DO NOT UPDATE THESE FILES OR CHANGE THE NAME, RATHER CREATE NEW ONCE
# These files have 2 purposes
# 1. they serve as unit tests
# 2. they can be used as discovery rules examples
####### HEADER END #######
apiVersion: inv.sdcio.dev/v1alpha1
kind: Schema
metadata:
  name: eos.arista.4.31.2.f
  namespace: default
spec:
  repoURL: https://github.com/aristanetworks/yang
  provider: eos.arista.sdcio.dev
  version: 4.31.2.F
  kind: branch
  ref: master
  dirs:
    - src: EOS-4.31.2F
      dst: .
  schema:
    models:
      - release/openconfig/models
    includes:
      - openconfig/public/release/models
      - iana/iana-if-type@2023-01-26.yang
      - ietf/ietf-inet-types.yang
      - ietf/ietf-interfaces.yang
      - ietf/ietf-yang-types.yang
    excludes:
      - .*notsupported.*