# DO NOT UPDATE THESE FILES OR CHANGE THE NAME, RATHER CREATE NEW ONCE
# These files have 2 purposes
# 1. they serve as unit tests
# 2. they can be used as discovery rules examples
####### HEADER END #######
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: dr-dynamic
  namespace: default
spec:
  period: 1m
  concurrentScans: 2
  prefixes:
  - prefix: 172.18.0.0/24
    excludes:
    - 172.18.0.0
    - 172.18.0.1
    - 172.18.0.255
  discoveryProfile:
    credentials: srl.nokia.sdcio.dev 
    connectionProfiles:
    - gnmi-skipverify
  targetConnectionProfiles:
  - credentials: srl.nokia.sdcio.dev 
    connectionProfile: gnmi-skipverify
    syncProfile: gnmi-get
  targetTemplate:
    labels:
      sdcio.dev/region: us-east
    
