apiVersion: v1
kind: ConfigMap
metadata:
  name: context
data: 
  configServerImage: europe-docker.pkg.dev/srlinux/eu.gcr.io/config-server
  dataServerImage: registry.kmrd.dev/iptecharch/data-server:latest
