apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: network-system
  labels:
    sdcio.dev/config-server: "true"
spec:
  ports:
  - name: api-service
    port: 6443
    targetPort: api-service
  selector:
    sdcio.dev/config-server: "true"
