apiVersion: v1
kind: Service
metadata:
  name: config-server-metrics
  namespace: network-system
  labels:
    app.kubernetes.io/name: config-server
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: config-server
